const CLOUD_NAME = import.meta.env.VITE_CLOUD_NAME;
const UPLOAD_PRESET = import.meta.env.VITE_UPLOAD_PRESET;

export const CLOUDINARY_CONFIG = {
  CLOUD_NAME: CLOUD_NAME,       
  UPLOAD_PRESET: UPLOAD_PRESET 
};
